#' Log Retained Commodities from Filtering (Elite Version)
#'
#' Logs retained commodity series from the filtering step to a timestamped CSV file,
#' and optionally to a detailed JSON metadata file for full audit trail.
#'
#' @param retained_df A data.frame with at least `commodity` and `n_obs` columns.
#' @param out_dir Directory where logs will be saved. Default: "logs/filter".
#' @param input_hash Optional SHA-256 hash of the original input file or data object.
#' @param run_id Optional 12-character short hash ID. If NULL, autogenerated from retained_df.
#' @param log_json Logical. If TRUE, write a companion metadata .json file. Default = TRUE.
#' @param tags Optional character vector (e.g., c("monthly", "TVAR-ready")).
#' @param note Optional freeform annotation. Default = "".
#' @param output_format One of "csv", "json", or "both". Default = "both".
#' @param verbose Logical. Whether to print summary and paths. Default = TRUE.
#'
#' @return Invisibly returns a list with file paths, run ID, and metadata.
#' @export
log_retained_commodities <- function(retained_df,
                                     out_dir = here::here("logs/filter"),
                                     input_hash = NULL,
                                     run_id = NULL,
                                     log_json = TRUE,
                                     tags = NULL,
                                     note = "",
                                     output_format = "both",
                                     verbose = TRUE) {
  stopifnot(is.data.frame(retained_df))
  stopifnot(all(c("commodity", "n_obs") %in% colnames(retained_df)))
  
  # hash + run ID 
  if (is.null(run_id)) {
    run_id <- substr(base64enc::base64encode(charToRaw(digest::digest(retained_df, algo = "sha256"))), 1, 12)
  }
  panel_hash <- digest::digest(retained_df, algo = "sha256")
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  
  # Output paths
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
  csv_path  <- file.path(out_dir, paste0("retained_commodities_", timestamp, "_", run_id, ".csv"))
  json_path <- file.path(out_dir, paste0("retained_commodities_", timestamp, "_", run_id, ".json"))
  
  # Compute optional date ranges (if `date` exists)
  has_date <- "date" %in% colnames(retained_df)
  if (has_date) {
    retained_df <- retained_df %>%
      dplyr::group_by(commodity) %>%
      dplyr::mutate(start_date = min(date, na.rm = TRUE),
                    end_date = max(date, na.rm = TRUE)) %>%
      dplyr::ungroup()
  }
  
  # Compute missingness (if `price` exists)
  if ("price" %in% colnames(retained_df)) {
    retained_df <- retained_df %>%
      dplyr::group_by(commodity) %>%
      dplyr::mutate(
        n_missing = sum(is.na(price)),
        pct_missing = round(100 * mean(is.na(price)), 2)
      ) %>%
      dplyr::ungroup()
  }
  
  # Save CSV 
  if (output_format %in% c("csv", "both")) {
    readr::write_csv(retained_df, csv_path)
  }
  
  # Save JSON metadata
  if (log_json || output_format %in% c("json", "both")) {
    metadata <- list(
      id = run_id,
      timestamp = format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z"),
      input_hash = input_hash,
      output_hash = panel_hash,
      n_retained = dplyr::n_distinct(retained_df$commodity),
      output_shape = list(rows = nrow(retained_df), columns = ncol(retained_df)),
      structure = list(
        colnames = names(retained_df),
        contains_date = has_date,
        contains_price = "price" %in% colnames(retained_df)
      ),
      session = list(
        user = Sys.info()[["user"]],
        pid = Sys.getpid(),
        platform = R.version$platform,
        version = R.version$version.string
      ),
      system = list(
        hostname = Sys.info()[["nodename"]],
        wd = getwd()
      ),
      tags = tags,
      note = note
    )
    
    jsonlite::write_json(metadata, path = json_path, pretty = TRUE, auto_unbox = TRUE)
  }
  
  # Verbose Output
  if (verbose) {
    cat("Retained commodities log complete.\n")
    if (output_format %in% c("csv", "both")) cat("📄 CSV saved to:", csv_path, "\n")
    if (log_json || output_format %in% c("json", "both")) cat("🧾 JSON metadata saved to:", json_path, "\n")
  }
  
  invisible(list(
    csv = if (output_format %in% c("csv", "both")) csv_path else NULL,
    json = if (log_json || output_format %in% c("json", "both")) json_path else NULL,
    id = run_id,
    hash = panel_hash
  ))
}
